Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-06, with the labels that each got.

#172 Hackathon 2020 many anufft cov2d
  src/aspire/basis/ffb_2d.py
  src/aspire/nfft/__init__.py
  src/aspire/nfft/cufinufft.py
  src/aspire/nfft/finufft.py
  tests/test_nfft.py
Labels: enhancement

#184 add git attibributes file
  .gitattributes
Labels: cleanup

#182 Fix pytest warnings
  src/aspire/basis/__init__.py
  src/aspire/basis/basis_utils.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/estimation/__init__.py
  src/aspire/estimation/covar.py
  src/aspire/estimation/kernel.py
  src/aspire/estimation/noise.py
  src/aspire/source/simulation.py
Labels: cleanup, good first issue

#188 Rough draft guidelines update
  CODEOWNERS
  CODING_GUIDELINES.md
Labels: CI, documentation, good first issue

#186 numpy norm
  src/aspire/source/simulation.py
  src/aspire/utils/matrix.py
Labels: cleanup

#191 Remove remaining uses of progress_bar
  requirements.txt
  setup.py
  src/aspire/aspire/class_averaging.py
  src/aspire/aspire/em_classavg/em.py
  src/aspire/aspire/em_classavg/test_progressbar2.py
  src/aspire/aspire/preprocessor.py
  src/aspire/aspire/utils/array_utils.py
  src/aspire/aspire/utils/compare_stacks.py
Labels: cleanup

#167 Downgrade the many framework of finufft to be consistent with FINufftPlan
  src/aspire/basis/polar_2d.py
  src/aspire/utils/misc.py
  tests/test_PolarBasis2D.py
Labels: enhancement

#197 Meld requirements.txt into setup.py and rm
  README.md
  environment.yml
  requirements.txt
  setup.py
Labels: cleanup
