Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-08, with the labels that each got.

#221 Apple Picker dtype
  src/aspire/apple/picking.py
Labels: CI, bug

#216 Seg Fault Issue 150
  src/aspire/utils/numeric/numpy.py
Labels: CI, bug, cleanup

#230 Nufft naming 223
  src/aspire/aspire/abinitio.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/polar_2d.py
  src/aspire/estimation/covar.py
  src/aspire/estimation/mean.py
  src/aspire/nufft/__init__.py
  src/aspire/nufft/cufinufft.py
  src/aspire/nufft/finufft.py
  src/aspire/nufft/pynfft.py
  src/aspire/nufft/utils.py
  src/aspire/utils/preprocess.py
  src/aspire/volume/__init__.py
  tests/test_nfft.py
Labels: cleanup

#190 unify the preprocess steps for experimental images
  src/aspire/image/__init__.py
  src/aspire/source/__init__.py
  src/aspire/source/relion.py
  src/aspire/source/xform.py
  src/aspire/utils/filters.py
  src/aspire/utils/matrix.py
  tutorials/examples/preprocess_imgs.py
Labels: enhancement
