Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-12, with the labels that each got.

#344 ship config with nworkers=1 to prevent oversub
  src/aspire/config.ini
Labels: bug, cleanup

#343 fix small import bug
  src/aspire/commands/preprocess.py
Labels: bug, cleanup

#298 includ centered fft functions in facade modules and replace FFT functions in other submodules
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/image/image.py
  src/aspire/image/preprocess.py
  src/aspire/noise/noise.py
  src/aspire/numeric/__init__.py
  src/aspire/numeric/base_fft.py
  src/aspire/numeric/cupy_fft.py
  src/aspire/numeric/pyfftw_fft.py
  src/aspire/numeric/scipy_fft.py
  src/aspire/volume/__init__.py
  tests/test_fft.py
Labels: enhancement

#335 Update readme
  README.md
  docs/source/installation.rst
  setup.py
Labels: cleanup, documentation, help wanted

#352 remove tests and tutorials from distribution manifest
  MANIFEST.in
Labels: cleanup

#325 Unit tests for Cov2d Denoiser
  src/aspire/denoising/denoised_src.py
  src/aspire/denoising/denoiser_cov2d.py
  tests/test_covar2d_denoiser.py
Labels: documentation, enhancement

#346 Reimplement real spherical harmonic function
  src/aspire/basis/basis_utils.py
  tutorials/examples/cov3d_simulation.py
Labels: enhancement

#355 Bump version patch
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
Labels: cleanup, documentation

#356 Add diagnostic lines to tox environments
  tox.ini
Labels: CI, documentation

#289 add unit tests for preprocess pipeline
  src/aspire/image/image.py
  src/aspire/operators/filters.py
  tests/test_preprocess_pipeline.py
Labels: enhancement

#361 Bump skimage, older version has a packaging bug.
  setup.py
Labels: bug, enhancement

#360 Add sphinx to Travis installs
  .bumpversion.cfg
  .travis.yml
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
Labels: CI, bug, cleanup, documentation

#314 Include Rotation class and unit tests
  src/aspire/utils/__init__.py
  src/aspire/utils/rotation.py
  tests/test_rotation.py
Labels: enhancement
