Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-05, with the labels that each got.

#147 Add an example contributors table in markdown
  CONTRIBUTORS.rst
  docs/source/authors.rst
  docs/source/index.rst
Labels: documentation, enhancement

#151 Include the Dirac and Polar Fourier basis Classes
  src/aspire/basis/__init__.py
  src/aspire/basis/dirac.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/polar_2d.py
  tests/saved_test_data/pfbasis_coefficients_8_4_32.npy
  tests/test_Diracbasis.py
  tests/test_PolarBasis2D.py
Labels: enhancement

#160 Disable CI for hack branch
  .travis.yml
  azure-pipelines.yml
Labels: wontfix
