Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-09, with the labels that each got.

#242 Remove the explicit requirement of dimension in Filter classes
  src/aspire/utils/filters.py
Labels: enhancement

#163 Include orientation estimation class using synchronization method
  src/aspire/config.ini
  src/aspire/orientation/__init__.py
  src/aspire/orientation/commonline_ev.py
  src/aspire/orientation/commonline_gcar.py
  src/aspire/orientation/commonline_lud.py
  src/aspire/orientation/commonline_sdp.py
  src/aspire/orientation/commonline_sync.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/matlab_compat.py
  src/aspire/utils/preprocess.py
  tests/saved_test_data/orient_est_clmatrix.npy
  tests/saved_test_data/orient_est_rots.npy
  tests/saved_test_data/orient_est_shifts.npy
  tests/saved_test_data/orient_est_smatrix.npy
  tests/test_coor_trans.py
  tests/test_orient_sync.py
  tests/test_preprocess.py
  tutorials/examples/orient3d_simulation.py
Labels: enhancement

#246 Issue 244 tutorials testing
  tests/test_tutorials.py
  tutorials/examples/cov2d_simulation.py
  tutorials/examples/cov3d_simulation.py
  tutorials/examples/image_expansion.py
  tutorials/examples/orient3d_simulation.py
Labels: documentation, enhancement

#254 Implement dual filter
  src/aspire/basis/__init__.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  tests/test_FBbasis2D.py
  tests/test_FBbasis3D.py
Labels: enhancement

#231 Col major To Row Major Conversion Round 1
  src/aspire/basis/__init__.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/polar_2d.py
  src/aspire/basis/pswf_2d.py
  src/aspire/estimation/__init__.py
  src/aspire/estimation/covar.py
  src/aspire/estimation/covar2d.py
  src/aspire/estimation/kernel.py
  src/aspire/estimation/noise.py
  src/aspire/image/__init__.py
  src/aspire/io/micrograph.py
  src/aspire/nufft/__init__.py
  src/aspire/nufft/cufinufft.py
  src/aspire/nufft/finufft.py
  src/aspire/orientation/__init__.py
  src/aspire/orientation/commonline_sync.py
  src/aspire/source/__init__.py
  src/aspire/source/mrcstack.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  src/aspire/source/xform.py
  src/aspire/utils/blk_diag_matrix.py
  src/aspire/utils/fft.py
  src/aspire/utils/misc.py
  src/aspire/utils/preprocess.py
  src/aspire/volume/__init__.py
  tests/saved_test_data/sim_blobs.npy
  tests/saved_test_data/sim_clean_images.npy
  tests/saved_test_data/sim_images_with_noise.npy
  tests/test_FBbasis2D.py
  tests/test_FFBbasis2D.py
  tests/test_FFBbasis3D.py
  tests/test_FPSWFbasis2D.py
  tests/test_PSWFbasis2D.py
  tests/test_PolarBasis2D.py
  tests/test_batched_covar2d.py
  tests/test_covar2d.py
  tests/test_covar3d.py
  tests/test_image.py
  tests/test_mean_estimator.py
  tests/test_micrograph.py
  tests/test_mrc_stack.py
  tests/test_nfft.py
  tests/test_orient_sync.py
  tests/test_preprocess.py
  tests/test_simulation.py
  tests/test_starfile_stack.py
  tutorials/examples/cov2d_simulation.py
  tutorials/examples/cov3d_simulation.py
  tutorials/examples/image_expansion.py
  tutorials/examples/orient3d_simulation.py
  tutorials/examples/preprocess_imgs.py
Labels: Optimization, cleanup, enhancement

#238 Remove casts in customized CG method
  src/aspire/utils/optimize.py
  tests/test_optimize.py
Labels: enhancement

#259 Replace imsave from scipy.misc with that from PIL
  setup.py
  src/aspire/apple/apple.py
  tests/test_apple.py
Labels: bug

#239 Use precomputed values for FB expansion of filter objects
  src/aspire/basis/ffb_2d.py
  src/aspire/utils/blk_diag_matrix.py
Labels: Optimization, enhancement

#274 Remove remaining non ascii chars in python files.
  src/aspire/orientation/__init__.py
  tutorials/examples/image_expansion.py
Labels: cleanup

#255 Implement DualFilter class
  src/aspire/utils/filters.py
  tests/test_filters.py
Labels: enhancement
