Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-11, with the labels that each got.

#300 Add a starfile IO unit test
  src/aspire/io/micrograph.py
  src/aspire/io/mrc.py
  src/aspire/io/starfile.py
  tests/test_mrc.py
  tests/test_starfileio.py
Labels: cleanup, documentation

#304 Make filter classes immutable
  src/aspire/source/__init__.py
  src/aspire/utils/filters.py
  tests/test_filters.py
Labels: enhancement

#318 Remove data folder from legacy code
  src/aspire/data/__init__.py
  src/aspire/data/bessel.npy
Labels: cleanup

#327 Ci updates
  setup.py
Labels: CI, bug, cleanup

#328 Patch mrc header label in unit test
  src/aspire/utils/misc.py
  tests/test_mrc.py
Labels: CI, bug

#319 cufinufft 1.1
  setup.py
  src/aspire/nufft/cufinufft.py
  tests/test_nfft.py
Labels: enhancement

#310 Random
  src/aspire/orientation/__init__.py
  src/aspire/source/simulation.py
  src/aspire/source/xform.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/matlab_compat.py
  src/aspire/utils/random.py
  tests/test_covar3d.py
  tests/test_orient_sync.py
  tests/test_random.py
  tutorials/examples/cov3d_simulation.py
Labels: cleanup

#339 add missing dtype for relion _image method
  src/aspire/source/relion.py
Labels: bug, cleanup

#333 tweak tox check settings for isort, no verbose
  tox.ini
Labels: CI

#312 Add CLICK command for preprocess steps
  src/aspire/commands/preprocess.py
Labels: enhancement

#342 latest flake8-bugbear fails on bare exceptions
  src/aspire/exceptions.py
  src/aspire/utils/misc.py
Labels: CI, bug, cleanup

#334 tighted up polar2d unit test
  tests/test_PolarBasis2D.py
Labels: CI, bug, cleanup
