Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2020-10, with the labels that each got.

#273 Fix downsample bug
  src/aspire/source/simulation.py
  tests/test_simulation.py
  tests/test_tutorials.py
  tutorials/examples/preprocess_imgs.py
Labels: bug

#278 Cleanup Block Diagonal Tests
  src/aspire/utils/blk_diag_matrix.py
  tests/test_BlkDiagMatrix.py
Labels: cleanup

#282 Add Volume Class Unit Tests
  src/aspire/estimation/covar.py
  src/aspire/source/simulation.py
  src/aspire/utils/misc.py
  src/aspire/volume/__init__.py
  tests/test_covar3d.py
  tests/test_utils.py
  tests/test_volume.py
Labels: cleanup, documentation, enhancement

#283 Remove legacy aspire/aspire code
  .bumpversion.cfg
  docs/source/conf.py
  src/aspire/aspire/__init__.py
  src/aspire/aspire/abinitio.py
  src/aspire/aspire/class_averaging.py
  src/aspire/aspire/common/__init__.py
  src/aspire/aspire/common/config.py
  src/aspire/aspire/common/logger.py
  src/aspire/aspire/em_classavg/__init__.py
  src/aspire/aspire/em_classavg/circ_shift_kernel.py
  src/aspire/aspire/em_classavg/config.py
  src/aspire/aspire/em_classavg/data_utils.py
  src/aspire/aspire/em_classavg/em.py
  src/aspire/aspire/em_classavg/em_old.py
  src/aspire/aspire/em_classavg/image_denoising/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/Converter.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/DirectModel/DirectModel.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/DirectModel/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/DirectModel/test.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/FastModel/FastModel.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/FastModel/FastModel_forward_utils.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/FastModel/FastModel_init_utils.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/FastModel/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/FastModel/test.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/test.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/ConverterModel/test_data/example_data_np_array.npy
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/BN/BN.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/BN/BN_init_utils.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/BN/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/GeneralFunctions.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/PSWF2DModel.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/PSWF2D_utils.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/PSWF2D/test.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/SteerablePCA.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/__init__.py
  src/aspire/aspire/em_classavg/image_denoising/image_denoising/enviroment.yml
  src/aspire/aspire/em_classavg/mask_images_kernel.py
  src/aspire/aspire/em_classavg/myplot.png
  src/aspire/aspire/em_classavg/s_em.py
  src/aspire/aspire/em_classavg/s_em_class_avg.py
  src/aspire/aspire/em_classavg/slice_assign_kernel.py
  src/aspire/aspire/em_classavg/test_forward_backward.py
  src/aspire/aspire/preprocessor.py
  src/aspire/aspire/utils/__init__.py
  src/aspire/aspire/utils/array_utils.py
  src/aspire/aspire/utils/compare_stacks.py
  src/aspire/aspire/utils/data_utils.py
  src/aspire/aspire/utils/helpers.py
  src/aspire/aspire/utils/parse_star.py
  src/aspire/aspire/utils/viewstack.py
  src/aspire/aspire/utils/workflow_validation.py
  src/aspire/commands/aspire.py
Labels: cleanup

#285 remove deprecated dependency
  setup.py
Labels: cleanup

#253 implement __str__ for Xform classes and improve Multiply and Shift Xforms
  src/aspire/source/__init__.py
  src/aspire/source/xform.py
  src/aspire/utils/filters.py
Labels: enhancement

#284 Separate normalization factor of FB basis into radial and angular parts
  src/aspire/basis/fb_2d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/utils/blk_diag_matrix.py
  tests/test_FBbasis2D.py
  tests/test_FFBbasis2D.py
Labels: enhancement

#269 normal fft modules for Pyfftw, Cupy and Scipy
  src/aspire/apple/helper.py
  src/aspire/apple/picking.py
  src/aspire/config.ini
  src/aspire/utils/numeric/__init__.py
  src/aspire/utils/numeric/cupy.py
  src/aspire/utils/numeric/cupy_fft.py
  src/aspire/utils/numeric/numpy.py
  src/aspire/utils/numeric/pyfftw_fft.py
  src/aspire/utils/numeric/scipy_fft.py
  tests/test_fft.py
Labels: enhancement

#288 Refresh logging
  pytest.ini
  src/aspire/__init__.py
  src/aspire/basis/polar_2d.py
  src/aspire/commands/cov3d.py
  src/aspire/commands/denoise.py
  src/aspire/config.ini
  src/aspire/exceptions.py
  src/aspire/logging.conf
  src/aspire/nufft/cufinufft.py
  src/aspire/orientation/__init__.py
  src/aspire/utils/misc.py
  tutorials/examples/cov2d_simulation.py
  tutorials/examples/cov3d_simulation.py
  tutorials/examples/image_expansion.py
  tutorials/examples/orient3d_simulation.py
  tutorials/examples/preprocess_imgs.py
Labels: cleanup, documentation, enhancement

#291 Fix bugs due to column to row changes for issue #290
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/estimation/covar2d.py
  src/aspire/io/starfile.py
  src/aspire/source/relion.py
  tests/test_batched_covar2d.py
Labels: bug

#295 Change to use filter types and indices
  src/aspire/estimation/covar2d.py
  src/aspire/source/__init__.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  src/aspire/source/xform.py
  tests/test_anisotropic_noise.py
  tests/test_batched_covar2d.py
  tests/test_covar2d.py
  tests/test_covar3d.py
  tests/test_mean_estimator.py
  tests/test_orient_sync.py
  tests/test_simulation.py
  tests/test_simulation_metadata.py
  tests/test_white_noise.py
  tutorials/examples/cov2d_simulation.py
  tutorials/examples/cov3d_simulation.py
  tutorials/examples/orient3d_simulation.py
  tutorials/examples/preprocess_imgs.py
Labels: enhancement

#305 Use IndexedXform for phase flip
  src/aspire/source/__init__.py
  src/aspire/source/xform.py
Labels: enhancement

#296 Resolve Dtypes
  src/aspire/apple/picking.py
  src/aspire/basis/__init__.py
  src/aspire/basis/basis_utils.py
  src/aspire/basis/dirac.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/polar_2d.py
  src/aspire/basis/pswf_2d.py
  src/aspire/basis/pswf_utils.py
  src/aspire/denoising/__init__.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/estimation/__init__.py
  src/aspire/estimation/covar.py
  src/aspire/estimation/covar2d.py
  src/aspire/estimation/kernel.py
  src/aspire/estimation/mean.py
  src/aspire/estimation/noise.py
  src/aspire/image/__init__.py
  src/aspire/io/micrograph.py
  src/aspire/io/starfile.py
  src/aspire/nufft/__init__.py
  src/aspire/nufft/finufft.py
  src/aspire/orientation/__init__.py
  src/aspire/orientation/commonline_sync.py
  src/aspire/source/__init__.py
  src/aspire/source/mrcstack.py
  src/aspire/source/simulation.py
  src/aspire/utils/blk_diag_matrix.py
  src/aspire/utils/cell.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/filters.py
  src/aspire/utils/matrix.py
  src/aspire/utils/misc.py
  src/aspire/utils/optimize.py
  src/aspire/utils/preprocess.py
  src/aspire/utils/types.py
  src/aspire/volume/__init__.py
  tests/test_FBbasis2D.py
  tests/test_FBbasis3D.py
  tests/test_FFBbasis2D.py
  tests/test_PolarBasis2D.py
  tests/test_batched_covar2d.py
  tests/test_covar2d.py
  tests/test_covar3d.py
  tests/test_filters.py
  tests/test_image.py
  tests/test_matrix.py
  tests/test_mean_estimator.py
  tests/test_nfft.py
  tests/test_orient_sync.py
  tests/test_utils.py
  tests/test_volume.py
  tutorials/examples/cov2d_simulation.py
  tutorials/examples/image_expansion.py
  tutorials/examples/orient3d_simulation.py
Labels: cleanup

#302 add preprocess example using experimental dataset
  tutorials/examples/preprocess_imgs_exp.py.dontrun
  tutorials/examples/preprocess_imgs_sim.py
Labels: documentation

#303 Add Cov2D tutorial example using experimental dataset
  tutorials/examples/cov2d_experiment.py.dontrun
Labels: documentation
