Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-09, with the labels that each got.

#451 Proposed README changeset
  README.md
Labels: documentation, cleanup

#449 ArrayImageSource admit numpy
  src/aspire/source/image.py
  tests/test_adaptive_support.py
  tests/test_array_image_source.py
Labels: cleanup

#452 Remove BlkDiagMatrix dense expansion in FSPCA compression
  src/aspire/basis/fspca.py
  src/aspire/operators/blk_diag_matrix.py
  tests/test_BlkDiagMatrix.py
Labels: enhancement, cleanup

#457 Bump version
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
Labels: documentation, CI

#456 fix oversight in `circ` and `inverse_r` centering
  src/aspire/utils/misc.py
Labels: bug

#461 add `make distclean` target to sphinx makefile
  docs/Makefile
Labels: bug, documentation

#462 FINUFFT should have fixed windows wheels now
  setup.py
Labels: CI
