Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-02, with the labels that each got.

#376 Replace Travis with Github Actions
  .github/workflows/workflow.yml
  .travis.yml
  README.md
  tox.ini
Labels: CI, enhancement

#337 Add CLICK command for orientation estimation
  src/aspire/abinitio/__init__.py
  src/aspire/abinitio/commonline_base.py
  src/aspire/abinitio/orientation_src.py
  src/aspire/commands/orient3d.py
Labels: enhancement

#354 Add tutorial example of orientation estimation using experimental dataset
  tutorials/examples/orient3d_experiment.dontrun
Labels: documentation, enhancement

#382 Add bibtex_bibfiles to docs conf
  docs/source/conf.py
Labels: bug, documentation

#386 Adds `aspire` cli entry point
  docs/source/quickstart.rst
  setup.py
  src/aspire/__main__.py
Labels: CI, enhancement

#388 remove unused skimage
  setup.py
Labels: cleanup

#329 Make noise variance consistent in the unit test of batched Cov2d class
  src/aspire/covariance/covar2d.py
  src/aspire/operators/blk_diag_matrix.py
  src/aspire/utils/__init__.py
  src/aspire/utils/matrix.py
  tests/saved_test_data/clean70SRibosome_cov2d_covarctf.npy
  tests/saved_test_data/clean70SRibosome_cov2d_cwf_coeff.npy
  tests/saved_test_data/clean70SRibosome_cov2d_cwf_coeff_noCTF.npy
  tests/test_batched_covar2d.py
Labels: documentation, enhancement

#383 Fix image array source
  src/aspire/source/__init__.py
  tutorials/examples/basic_image_array.py
Labels: bug, enhancement

#391 Github Pages Documentation Using actions
  .github/workflows/workflow.yml
  MANIFEST.in
  docs/buildsite.sh
  docs/source/conf.py
  setup.py
Labels: CI, cleanup, documentation, enhancement

#390 FFB3d debugging
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/reconstruction/estimator.py
  src/aspire/utils/matrix.py
  tests/test_FBbasis3D.py
  tests/test_covar3d.py
Labels: bug, enhancement
