Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-10, with the labels that each got.

#471 Fix ctf cli arg bug
  src/aspire/commands/estimate_ctf.py
  src/aspire/ctf/ctf_estimator.py
Labels: bug, CLI

#467 Batching causing Numpy error in `DenoisedImageSource`
  src/aspire/denoising/denoised_src.py
Labels: bug

#479 Add simple alignments and supporting code
  gallery/tutorials/class_averaging.py
  src/aspire/basis/fspca.py
  src/aspire/basis/steerable.py
  src/aspire/classification/__init__.py
  src/aspire/classification/align2d.py
  src/aspire/classification/class2d.py
  src/aspire/classification/legacy_implementations.py
  src/aspire/classification/rir_class2d.py
  src/aspire/utils/rotation.py
  tests/test_FFBbasis2D.py
  tests/test_align2d.py
  tests/test_class2D.py
Labels: bug, enhancement, question, cleanup
