Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-12, with the labels that each got.

#527 Change the max diff computation in tutorials
  gallery/tutorials/image_expansion.py
Labels: bug, documentation, cleanup

#530 Roll stable MacOS tests to 10.15 from 10.14
  azure-pipelines.yml
Labels: bug, CI, extern

#517 Redundant method `eval_filter_grid` in `ImageSource`
  src/aspire/covariance/covar.py
  src/aspire/operators/__init__.py
  src/aspire/operators/filters.py
  src/aspire/reconstruction/mean.py
  src/aspire/source/image.py
Labels: cleanup

#529 Avoid deprecation warnings in `importlib_resources`
  src/aspire/__init__.py
  src/aspire/utils/importlib_legacy.py
  tests/test_apple.py
  tests/test_micrograph.py
  tests/test_mrc_stack.py
  tests/test_starfile_stack.py
  tests/test_starfileio.py
Labels: CI, cleanup

#532 ImageSource Length
  src/aspire/source/image.py
Labels: enhancement
