Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-11, with the labels that each got.

#486 Refactor `test_starfile_stack.py`
  tests/saved_test_data/sample_relion_one_image.star
  tests/test_starfile_stack.py
Labels: cleanup

#498 Noise Filter scale
  gallery/experiments/cov2d_experiment.py.dontrun
  src/aspire/commands/denoise.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/noise/noise.py
  tests/test_anisotropic_noise.py
Labels: bug, help wanted

#507 Set default noise est to White in both CLI and experiment
  src/aspire/commands/denoise.py
  src/aspire/denoising/denoiser_cov2d.py
Labels: cleanup

#510 Bump version: 0.8.0 → 0.8.1
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
Labels: documentation

#514 Volume Save Function 367
  src/aspire/volume/__init__.py
  tests/test_volume.py
Labels: enhancement
