Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2021-01, with the labels that each got.

#370 Use nufft "many" interface in 3D calls
  src/aspire/basis/ffb_3d.py
Labels: Optimization, enhancement

#366 Change the option to load numeric modules
  src/aspire/config.ini
  src/aspire/numeric/__init__.py
  tests/test_fft.py
Labels: enhancement

#348 include tutorial example for Cov3d using experimental data
  tutorials/examples/cov3d_experiment.dontrun
Labels: documentation, enhancement

#374 Cast convolution result to real
  src/aspire/reconstruction/kernel.py
Labels: bug

#368 Separate save function into save_metedata and save_images
  src/aspire/source/__init__.py
  src/aspire/storage/__init__.py
  src/aspire/storage/starfile.py
  tests/test_simulation.py
  tests/test_starfileio.py
Labels: enhancement
