Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-12, with the labels that each got.

#776 Simplify Fourier-Bessel basis list of zeros
  src/aspire/basis/fb.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/utils/filter_to_fb_mat.py
  tests/test_FBbasis2D.py
  tests/test_FFBbasis2D.py
Labels: cleanup

#794 Sim/Vol dtype passthrough
  src/aspire/source/simulation.py
  src/aspire/volume/volume.py
  tests/test_simulation.py
  tests/test_volume.py
Labels: bug, cleanup

#778 Parameterized tests fix 774
  tests/test_FBbasis2D.py
  tests/test_FFBbasis2D.py
Labels: bug, cleanup

#796 Enforcing `_evaluate_t` and `_evaluate` signatures
  src/aspire/basis/basis.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/polar_2d.py
Labels: cleanup

#799 Remove regexp match on sklearn error messages
  tests/test_complexPCA.py
Labels: bug, CI

#790 Parallel BFS
  src/aspire/classification/averager2d.py
  src/aspire/classification/rir_class2d.py
  tests/test_averager2d.py
  tests/test_class2D.py
Labels: enhancement, cleanup

#802 Develop ~> Master - More CI patches
  src/aspire/basis/basis.py
  src/aspire/basis/fb.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/polar_2d.py
  src/aspire/classification/averager2d.py
  src/aspire/classification/rir_class2d.py
  src/aspire/source/simulation.py
  src/aspire/utils/filter_to_fb_mat.py
  src/aspire/volume/volume.py
  tests/test_FBbasis2D.py
  tests/test_FFBbasis2D.py
  tests/test_averager2d.py
  tests/test_class2D.py
  tests/test_complexPCA.py
  tests/test_simulation.py
  tests/test_volume.py
Labels: CI, extern

#791 Multi dimensional stack axis
  src/aspire/basis/basis.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/image/image.py
  src/aspire/image/xform.py
  src/aspire/source/image.py
  src/aspire/volume/volume.py
  tests/test_FFBbasis2D.py
  tests/test_bispectrum.py
  tests/test_image.py
  tests/test_starfileio.py
  tests/test_volume.py
Labels: enhancement, cleanup

#804 Bump Function Division by Zero Warning
  src/aspire/utils/misc.py
Labels: bug

#769 Symmetric Volume Tests
  src/aspire/volume/volume_synthesis.py
  tests/test_synthetic_volume.py
Labels: enhancement, CI

#808 ctf estimate fix
  src/aspire/ctf/ctf_estimator.py
  tests/test_CtfEstimate.py
Labels: bug, cleanup

#795 Logging configuration through ASPIRE config file (`confuse`)
  gallery/tutorials/configuration.py
  src/aspire/__init__.py
  src/aspire/commands/__init__.py
  src/aspire/commands/apple.py
  src/aspire/commands/cov3d.py
  src/aspire/commands/denoise.py
  src/aspire/commands/estimate_ctf.py
  src/aspire/commands/extract_particles.py
  src/aspire/commands/orient3d.py
  src/aspire/commands/preprocess.py
  src/aspire/config_default.yaml
  src/aspire/logging.conf
  src/aspire/utils/logging.py
Labels: documentation, enhancement

#807 Averager unit test bug fixes
  src/aspire/classification/averager2d.py
  src/aspire/utils/rotation.py
  tests/test_averager2d.py
Labels: bug, help wanted, CI

#800 Daily docs build
  .github/workflows/daily_workflow.yml
Labels: documentation, CI

#813 Normalize background dtype bug
  src/aspire/image/image.py
  tests/test_preprocess_pipeline.py
Labels: bug, CI, cleanup

#805 Add `coefficient_dtype` property to `Basis` to enforce input and output types for `evaluate` and `evaluate_t`
  src/aspire/basis/basis.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/polar_2d.py
  src/aspire/basis/pswf_2d.py
  tests/_basis_util.py
Labels: enhancement, cleanup
