Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-05, with the labels that each got.

#615 Zenodo file with authors and affiliations
  .zenodo.json
  MANIFEST.in
  tox.ini
Labels: documentation

#625 update scikit-learn workaround
  src/aspire/numeric/complex_pca/validation.py
  tests/test_complexPCA.py
Labels: bug

#632 Fix PIL deprecation warning
  src/aspire/apple/picking.py
  src/aspire/storage/micrograph.py
Labels: CI, cleanup, extern
