Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-10, with the labels that each got.

#708 use the dtype from volume in simulated pipeline
  gallery/experiments/simulated_abinitio_pipeline.py
Labels: documentation, cleanup

#706 Add top level import of submodules
  src/aspire/__init__.py
Labels: good first issue, CI, cleanup

#709 `evaluate_t()` NumPy warnings
  src/aspire/basis/basis.py
  src/aspire/covariance/covar2d.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/reconstruction/estimator.py
  tests/_basis_util.py
  tests/test_FBbasis2D.py
  tests/test_FFBbasis3D.py
Labels: cleanup

#689 3D Downsampling
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/orient3d_simulation.py
  gallery/tutorials/preprocess_imgs_sim.py
  src/aspire/volume/__init__.py
  tests/test_covar2d.py
  tests/test_downsample.py
  tests/test_orient_sync.py
  tests/test_volume.py
Labels: enhancement, cleanup

#681 Refactor of image accessor API for `ImageSource`
  gallery/experiments/experimental_abinitio_pipeline.py
  gallery/experiments/preprocess_imgs_exp.py.dontrun
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/basic_image_array.py
  gallery/tutorials/class_averaging.py
  gallery/tutorials/cov2d_simulation.py
  gallery/tutorials/generating_volume_projections.py
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/preprocess_imgs_sim.py
  gallery/tutorials/starfile.py
  src/aspire/abinitio/commonline_base.py
  src/aspire/abinitio/orientation_src.py
  src/aspire/basis/fspca.py
  src/aspire/classification/averager2d.py
  src/aspire/covariance/covar.py
  src/aspire/covariance/covar2d.py
  src/aspire/denoising/adaptive_support.py
  src/aspire/denoising/denoised_src.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/noise/noise.py
  src/aspire/reconstruction/estimator.py
  src/aspire/source/coordinates.py
  src/aspire/source/image.py
  src/aspire/source/mrcstack.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  tests/test_FFBbasis2D.py
  tests/test_array_image_source.py
  tests/test_averager2d.py
  tests/test_batched_covar2d.py
  tests/test_bispectrum.py
  tests/test_class2D.py
  tests/test_coordinate_source.py
  tests/test_covar2d.py
  tests/test_covar2d_denoiser.py
  tests/test_downsample.py
  tests/test_load_images.py
  tests/test_mrc_stack.py
  tests/test_preprocess_pipeline.py
  tests/test_simulation.py
  tests/test_starfile_stack.py
Labels: enhancement

#716 update sphinx conf `language`
  docs/source/conf.py
Labels: cleanup

#723 Bump version: 0.9.2 → 0.10.0
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
Labels: documentation, CI

#725 Cleanup ctf est units
  src/aspire/ctf/ctf_estimator.py
Labels: bug, documentation, cleanup

#717 Add garrett to codeowners
  CODEOWNERS
Labels: CI

#695 Batched cls avg
  src/aspire/basis/fspca.py
  src/aspire/classification/rir_class2d.py
  tests/test_class2D.py
Labels: enhancement, cleanup

#704 Fix Docstrings Formatting
  src/aspire/apple/apple.py
  src/aspire/apple/helper.py
  src/aspire/basis/basis.py
  src/aspire/basis/basis_utils.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/ffb_2d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/fspca.py
  src/aspire/basis/polar_2d.py
  src/aspire/basis/pswf_2d.py
  src/aspire/classification/averager2d.py
  src/aspire/classification/rir_class2d.py
  src/aspire/covariance/covar.py
  src/aspire/covariance/covar2d.py
  src/aspire/denoising/denoiser_cov2d.py
  src/aspire/image/preprocess.py
  src/aspire/image/xform.py
  src/aspire/noise/noise.py
  src/aspire/nufft/finufft.py
  src/aspire/operators/blk_diag_matrix.py
  src/aspire/operators/filters.py
  src/aspire/optimization/conj_grad.py
  src/aspire/reconstruction/estimator.py
  src/aspire/reconstruction/kernel.py
  src/aspire/source/image.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/fft.py
  src/aspire/utils/filter_to_fb_mat.py
  src/aspire/utils/matrix.py
  src/aspire/volume/__init__.py
Labels: documentation, cleanup

#714 Dtype cleanup
  src/aspire/image/image.py
  src/aspire/nufft/__init__.py
  src/aspire/source/simulation.py
  src/aspire/utils/types.py
  src/aspire/volume/__init__.py
  tests/_basis_util.py
  tests/test_FFBbasis2D.py
  tests/test_FFBbasis3D.py
  tests/test_FPSWFbasis2D.py
  tests/test_PSWFbasis2D.py
Labels: cleanup

#728 fixup covar2d ells mask
  src/aspire/covariance/covar2d.py
Labels: cleanup, Optimization

#722 Build Gallery without Running
  docs/Makefile
  docs/source/conf.py
Labels: documentation, enhancement
