Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-01, with the labels that each got.

#540 add missing python version 3.10 to installation rst
  docs/source/installation.rst
Labels: documentation, cleanup

#535 Replace importlib_resources with importlib.resources
  setup.py
  src/aspire/__init__.py
  src/aspire/utils/importlib_legacy.py
  tests/test_apple.py
  tests/test_micrograph.py
  tests/test_mrc_stack.py
  tests/test_starfile_stack.py
  tests/test_starfileio.py
Labels: CI, cleanup

#536 Remove orientation estimation setting from config
  src/aspire/abinitio/commonline_base.py
  src/aspire/abinitio/commonline_sync.py
  src/aspire/commands/orient3d.py
  src/aspire/config.ini
  tests/test_orient_sync.py
Labels: enhancement, cleanup, CLI

#499 Gaussian volume 494 functions
  src/aspire/source/simulation.py
  src/aspire/utils/misc.py
  src/aspire/utils/rotation.py
  src/aspire/volume/__init__.py
  tests/test_utils.py
  tests/test_volume.py
Labels: enhancement

#523 Grid indexing
  src/aspire/basis/basis_utils.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/denoising/adaptive_support.py
  src/aspire/image/image.py
  src/aspire/noise/noise.py
  src/aspire/operators/filters.py
  src/aspire/reconstruction/mean.py
  src/aspire/source/image.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/misc.py
  src/aspire/volume/__init__.py
  tests/test_FFBbasis2D.py
  tests/test_coor_trans.py
  tests/test_grids.py
  tests/test_preprocess_pipeline.py
Labels: enhancement, cleanup

#520 CoordinateSource -- class factory pattern refactor
  src/aspire/commands/extract_particles.py
  src/aspire/source/__init__.py
  src/aspire/source/coordinates.py
  tests/test_coordinate_source.py
Labels: enhancement
