Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-02, with the labels that each got.

#552 update codebase to conform with latest black release: 22.1.0
  gallery/tutorials/basic_image_array.py
  gallery/tutorials/class_averaging.py
  gallery/tutorials/lecture_feature_demo.py
  src/aspire/abinitio/commonline_base.py
  src/aspire/abinitio/commonline_sync.py
  src/aspire/apple/apple.py
  src/aspire/apple/helper.py
  src/aspire/apple/picking.py
  src/aspire/basis/dirac.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/steerable.py
  src/aspire/covariance/covar.py
  src/aspire/covariance/covar2d.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/image/image.py
  src/aspire/image/preprocess.py
  src/aspire/noise/noise.py
  src/aspire/operators/filters.py
  src/aspire/optimization/conj_grad.py
  src/aspire/reconstruction/kernel.py
  src/aspire/reconstruction/mean.py
  src/aspire/source/simulation.py
  src/aspire/storage/micrograph.py
  src/aspire/utils/matrix.py
  src/aspire/utils/misc.py
  src/aspire/volume/__init__.py
  tests/test_BlkDiagMatrix.py
  tests/test_adaptive_support.py
  tests/test_filters.py
  tests/test_preprocess_pipeline.py
  tests/test_utils.py
  tests/test_volume.py
  tests/test_wbemd.py
Labels: CI

#537 Candidate fix for #533: Whitening applied twice to `Simulation` objects
  src/aspire/source/image.py
  src/aspire/source/simulation.py
Labels: bug, help wanted, question, cleanup

#551 Add preprocessing flags to `aspire extract-particles`
  src/aspire/commands/extract_particles.py
  src/aspire/commands/preprocess.py
  tests/test_coordinate_source.py
Labels: enhancement

#571 Update authors for this release
  CONTRIBUTORS.rst
Labels: documentation, cleanup

#575 Force finufft signals to be complex
  src/aspire/nufft/finufft.py
Labels: bug, good first issue, CI

#538 Align2D refactor/updates
  docs/source/conf.py
  gallery/experiments/README.rst
  gallery/experiments/experimental_abinitio_pipeline.py
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/class_averaging.py
  setup.py
  src/aspire/basis/basis.py
  src/aspire/classification/__init__.py
  src/aspire/classification/align2d.py
  src/aspire/classification/averager2d.py
  src/aspire/classification/class2d.py
  src/aspire/classification/rir_class2d.py
  src/aspire/covariance/covar.py
  src/aspire/covariance/covar2d.py
  src/aspire/denoising/__init__.py
  src/aspire/denoising/denoised_src.py
  src/aspire/denoising/denoiser_cov2d.py
  tests/test_averager2d.py
  tests/test_class2D.py
Labels: enhancement, cleanup

#582 `CoordinateSource` patches
  src/aspire/source/coordinates.py
  tests/test_coordinate_source.py
Labels: bug

#583 Deprecate ensure
  src/aspire/abinitio/commonline_sync.py
  src/aspire/basis/basis.py
  src/aspire/basis/basis_utils.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/polar_2d.py
  src/aspire/covariance/covar.py
  src/aspire/covariance/covar2d.py
  src/aspire/image/image.py
  src/aspire/image/preprocess.py
  src/aspire/nufft/cufinufft.py
  src/aspire/nufft/finufft.py
  src/aspire/nufft/pynfft.py
  src/aspire/operators/filters.py
  src/aspire/reconstruction/kernel.py
  src/aspire/source/image.py
  src/aspire/source/simulation.py
  src/aspire/storage/micrograph.py
  src/aspire/utils/__init__.py
  src/aspire/utils/matrix.py
  src/aspire/utils/misc.py
  src/aspire/utils/rotation.py
  src/aspire/volume/__init__.py
Labels: cleanup
