Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-09, with the labels that each got.

#623 `estimate_ctf` integration with `CoordinateSource`
  src/aspire/ctf/ctf_estimator.py
  src/aspire/source/coordinates.py
  src/aspire/utils/relion_interop.py
  tests/test_CtfEstimate.py
  tests/test_coordinate_source.py
Labels: enhancement, cleanup

#692 Fix vol flip axis 691
  src/aspire/source/simulation.py
  src/aspire/volume/__init__.py
  tests/test_volume.py
Labels: bug, cleanup

#686 Batched cov2d noctf patch
  src/aspire/covariance/covar2d.py
  tests/test_batched_covar2d.py
  tests/test_covar2d.py
Labels: bug, cleanup

#614 In-plane rotations
  src/aspire/abinitio/commonline_c3_c4.py
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  tests/test_orient_symmetric.py
Labels: enhancement
