Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-07, with the labels that each got.

#649 Refactor `ainner` to handle complex values
  src/aspire/utils/matrix.py
Labels: bug

#648 Fix `Image.set_metadata()` bug
  src/aspire/source/image.py
Labels: bug, cleanup

#656 `Filter.sign` method
  src/aspire/operators/filters.py
  src/aspire/source/image.py
  tests/test_filters.py
Labels: enhancement

#655 Update Getting Started page
  docs/source/quickstart.rst
  docs/source/references.bib
  src/aspire/commands/preprocess.py
Labels: documentation, cleanup

#657 Simplify `gaussian_` functions
  gallery/tutorials/class_averaging.py
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  tests/_basis_util.py
  tests/test_adaptive_support.py
  tests/test_utils.py
Labels: cleanup
