Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-03, with the labels that each got.

#590 BFSReddyChetterji k Bug
  src/aspire/classification/averager2d.py
Labels: bug, cleanup

#550 Change `self.L` and `self.n` to `self.src.L` and `self.src.n` for estimators
  src/aspire/covariance/covar.py
  src/aspire/noise/noise.py
  src/aspire/reconstruction/estimator.py
  src/aspire/reconstruction/mean.py
Labels: cleanup

#565 Add `aspire.utils.coor_trans.crop_2d` and move `coor_trans` objects to second-level API access
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/orient3d_simulation.py
  src/aspire/abinitio/commonline_base.py
  src/aspire/basis/basis_utils.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/denoising/adaptive_support.py
  src/aspire/image/image.py
  src/aspire/noise/noise.py
  src/aspire/operators/filters.py
  src/aspire/source/image.py
  src/aspire/source/simulation.py
  src/aspire/utils/__init__.py
  src/aspire/utils/coor_trans.py
  src/aspire/utils/misc.py
  src/aspire/volume/__init__.py
  tests/test_coor_trans.py
  tests/test_grids.py
  tests/test_preprocess_pipeline.py
  tests/test_volume.py
Labels: enhancement

#596 Bessel zero finding cleanup
  src/aspire/basis/basis.py
  src/aspire/basis/basis_utils.py
Labels: cleanup

#598 `Basis` size fixes
  src/aspire/basis/basis.py
  src/aspire/basis/dirac.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fb_3d.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/basis/polar_2d.py
  src/aspire/basis/pswf_2d.py
  tests/test_Diracbasis.py
  tests/test_FBbasis2D.py
  tests/test_FBbasis3D.py
  tests/test_FPSWFbasis2D.py
  tests/test_PSWFbasis2D.py
  tests/test_PolarBasis2D.py
Labels: bug
