Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2022-11, with the labels that each got.

#721 Use `about_axis()` and `Volume.load()` in gallery
  gallery/tutorials/cov2d_simulation.py
  gallery/tutorials/generating_volume_projections.py
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/orient3d_simulation.py
  gallery/tutorials/preprocess_imgs_sim.py
Labels: documentation, cleanup

#718 Remove `Micrograph` and `MrcStack` classes in favor of `ImageSource`
  src/aspire/source/mrcstack.py
  src/aspire/storage/__init__.py
  src/aspire/storage/micrograph.py
  tests/test_micrograph.py
  tests/test_mrc_stack.py
Labels: cleanup

#719 Return info dictionary from `ImageSource.save()`
  src/aspire/source/image.py
  tests/test_simulation.py
Labels: enhancement

#726 GPU CI
  .github/workflows/workflow.yml
  README.md
  docs/source/installation.rst
  setup.py
  src/aspire/config.ini
  src/aspire/nufft/cufinufft.py
Labels: enhancement, CI, Optimization, GPU

#741 Use `ImageAccessor` to access class images in `Averager2D`
  src/aspire/classification/averager2d.py
  src/aspire/source/image.py
Labels: cleanup

#737 Unified `transpose` and `flip` API for Volume and Image
  src/aspire/image/image.py
  src/aspire/volume/__init__.py
  tests/test_image.py
Labels: cleanup

#732 Insert particle coordinates into `CoordinateSource` metadata
  gallery/experiments/orient3d_experiment.dontrun
  src/aspire/commands/orient3d.py
  src/aspire/source/coordinates.py
  src/aspire/source/image.py
  tests/test_coordinate_source.py
Labels: enhancement

#740 Change the most spammy logs to `debug` and add progress bars in place.
  src/aspire/classification/rir_class2d.py
  src/aspire/image/xform.py
  src/aspire/noise/noise.py
  src/aspire/source/image.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
Labels: cleanup

#750 only run gpu ci job after check passes
  .github/workflows/workflow.yml
Labels: CI, cleanup

#754 Importlib path
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  tests/test_apple.py
  tests/test_coordinate_source.py
  tests/test_starfile_stack.py
  tests/test_starfileio.py
Labels: cleanup, extern, Python 3.11, dependencies

#713 Pipeline Demo Tutorial
  docs/source/conf.py
  gallery/tutorials/pipeline_demo.py
  setup.py
  src/aspire/abinitio/commonline_sync.py
  src/aspire/image/image.py
Labels: documentation

#751 commonline orient est dtype passthrough check
  tests/test_orient_sync.py
Labels: bug, cleanup

#757 add scale colorbar to show
  src/aspire/image/image.py
Labels: enhancement

#759 Add pytest-xdist to dev tools extras
  setup.py
Labels: enhancement

#749 Config Cleanup
  .bumpversion.cfg
  MANIFEST.in
  gallery/tutorials/configuration.py
  setup.py
  src/aspire/__init__.py
  src/aspire/classification/averager2d.py
  src/aspire/config.ini
  src/aspire/config/__init__.py
  src/aspire/config_default.yaml
  src/aspire/covariance/covar.py
  src/aspire/nufft/__init__.py
  src/aspire/numeric/__init__.py
  src/aspire/reconstruction/estimator.py
  tests/test_config.py
  tests/test_fft.py
  tox.ini
Labels: enhancement, cleanup

#659 ABC Volume Synthesis
  gallery/tutorials/cov3d_simulation.py
  gallery/tutorials/generating_volume_projections.py
  src/aspire/source/simulation.py
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  src/aspire/utils/rotation.py
  src/aspire/volume/__init__.py
  src/aspire/volume/volume.py
  src/aspire/volume/volume_synthesis.py
  tests/test_rotation.py
  tests/test_simulation.py
  tests/test_synthetic_volume.py
  tests/test_utils.py
  tests/test_volume.py
Labels: enhancement

#755 Bfrs coefs
  src/aspire/classification/averager2d.py
  tests/test_averager2d.py
Labels: cleanup, Optimization

#763 FFT cleanup
  src/aspire/config_default.yaml
  src/aspire/covariance/covar.py
  src/aspire/numeric/base_fft.py
  src/aspire/numeric/pyfftw_fft.py
  src/aspire/reconstruction/kernel.py
  src/aspire/reconstruction/mean.py
  src/aspire/utils/fft.py
Labels: bug, enhancement, cleanup

#765 Bump version: 0.10.0 → 0.10.1
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  src/aspire/__init__.py
  src/aspire/config_default.yaml
Labels: documentation, CI

#736 Real Coefficient Rotation
  gallery/tutorials/class_averaging.py
  src/aspire/basis/fb_2d.py
  src/aspire/basis/fspca.py
  src/aspire/basis/steerable.py
  src/aspire/classification/averager2d.py
  src/aspire/classification/reddy_chatterji.py
  tests/test_FFBbasis2D.py
  tests/test_averager2d.py
Labels: documentation, enhancement, cleanup

#777 Pin pytest to 7.1.3 to see if resolves Azure hangs
  setup.py
Labels: bug, CI, extern

#761 Make gauss_2d/3d more consistent
  src/aspire/utils/misc.py
  tests/test_utils.py
Labels: cleanup

#775 Remove `_im_translate2` and improve shifting tests
  src/aspire/image/__init__.py
  src/aspire/image/image.py
  tests/test_image.py
Labels: bug, cleanup

#773 Cleanup `preprocess.py`
  src/aspire/image/__init__.py
  src/aspire/image/preprocess.py
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  tests/test_preprocess.py
  tests/test_utils.py
  tests/test_volume.py
Labels: cleanup

#771 update GitHub Actions checkout, setup, and codecov versions to v3
  .github/workflows/workflow.yml
  README.md
  azure-pipelines.yml
  docs/source/installation.rst
  environment.yml
Labels: good first issue, CI, cleanup, extern
