Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-11, with the labels that each got.

#1032 PSWF 2D Grid Construction
  src/aspire/basis/pswf_2d.py
Labels: cleanup

#1035 Add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, support

#1040 tmp extend develop timeout to 12 hours
  .github/workflows/long_workflow.yml
Labels: CI

#1037 add author note and paper to ctf module
  src/aspire/ctf/ctf_estimator.py
Labels: documentation, good first issue, support

#1043 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, cleanup

#1047 increase sample_n for small class averaging problems
  tests/test_class_src.py
Labels: CI

#1050 Flaky Sync Voting Test
  tests/test_orient_sync_voting.py
Labels: CI

#1051 use magnitude of eigvals in bispect random vector selection
  src/aspire/classification/legacy_implementations.py
Labels: CI, cleanup

#1053 Revert "use magnitude of eigvals in bispect random vector selection"
  src/aspire/classification/legacy_implementations.py
Labels: CI

#1055 Fix CI, update filter._evaluate arg order.
  src/aspire/operators/filters.py
Labels: CI, cleanup
