Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-01, with the labels that each got.

#820 Change `tox.ini` to follow external command rules for `tox 4.x`
  tox.ini
Labels: bug, CI

#826 Workaround scipy 1.10.0 dtype bug 17718
  src/aspire/operators/filters.py
Labels: bug, CI, extern

#821 Dtype of `Simulation.filter_indices`
  src/aspire/source/coordinates.py
  src/aspire/source/simulation.py
Labels: bug

#817 `CTFEstimator` has incorrect column name in STAR output
  src/aspire/ctf/ctf_estimator.py
  tests/test_CtfEstimate.py
Labels: invalid, cleanup

#768 Simulation NoiseAdder
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/basic_image_array.py
  gallery/tutorials/class_averaging.py
  gallery/tutorials/cov2d_simulation.py
  gallery/tutorials/generating_volume_projections.py
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/pipeline_demo.py
  gallery/tutorials/preprocess_imgs_sim.py
  src/aspire/image/xform.py
  src/aspire/noise/__init__.py
  src/aspire/noise/noise.py
  src/aspire/operators/filters.py
  src/aspire/source/simulation.py
  src/aspire/utils/__init__.py
  tests/test_batched_covar2d.py
  tests/test_class2D.py
  tests/test_covar2d.py
  tests/test_covar2d_denoiser.py
  tests/test_noise.py
  tests/test_preprocess_pipeline.py
  tests/test_simulation.py
  tests/test_white_noise.py
Labels: enhancement, cleanup

#829 Update randomized unit test that was flaky under float32
  tests/test_noise.py
Labels: bug, CI

#830 Develop
  tests/test_noise.py
Labels: bug, CI

#834 Update randomized unit test that was flaky after running large trial
  tests/test_noise.py
Labels: CI, cleanup

#835 Sync Master to Develop
  tests/test_noise.py
Labels: CI

#824 Simulation default volume 811
  gallery/tutorials/cov3d_simulation.py
  src/aspire/source/simulation.py
  src/aspire/volume/volume_synthesis.py
  tests/test_anisotropic_noise.py
  tests/test_covar3d.py
  tests/test_mean_estimator.py
  tests/test_simulation.py
Labels: cleanup

#837 Tox and Docs 828
  tox.ini
Labels: documentation, CI

#815 Drop `parameterized_class` from `test_image`
  tests/test_image.py
Labels: CI, cleanup

#841 Polar Fourier - Row Major (662)
  src/aspire/abinitio/commonline_base.py
  src/aspire/abinitio/commonline_c3_c4.py
Labels: cleanup

#840 Common Lines: `n_theta` even check
  src/aspire/abinitio/commonline_base.py
  src/aspire/basis/polar_2d.py
  tests/test_PolarBasis2D.py
  tests/test_orient_sync.py
Labels: bug

#845 V estimator
  src/aspire/abinitio/commonline_cn.py
  tests/test_orient_symmetric.py
Labels: enhancement, help wanted, theory

#818 Drop `parameterized_class` from `FBBasis2D` and `FFBBasis2D`
  tests/_basis_util.py
  tests/test_FBbasis2D.py
  tests/test_FBbasis3D.py
  tests/test_FFBbasis2D.py
  tests/test_FFBbasis3D.py
  tests/test_FPSWFbasis2D.py
  tests/test_PSWFbasis2D.py
  tests/test_PolarBasis2D.py
Labels: CI, cleanup
