Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-12, with the labels that each got.

#1062 Bump version to 0.12.1
  .bumpversion.cfg
  README.md
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
  src/aspire/__init__.py
  src/aspire/config_default.yaml
Labels: documentation

#1065 Workaround Ray dependency conflict
  pyproject.toml
Labels: bug, extern, dependencies

#1067 Fix incorrect basis in Coef wrapper
  src/aspire/basis/fspca.py
Labels: bug, cleanup
