Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-04, with the labels that each got.

#900 Remove redundant Image conversion bug in denoised_src (cov2d)
  src/aspire/denoising/denoised_src.py
Labels: bug, cleanup

#895 LogFilterByCount
  src/aspire/nufft/__init__.py
  src/aspire/utils/__init__.py
  src/aspire/utils/logging.py
  tests/test_utils.py
Labels: enhancement, cleanup, Optimization

#866 Class Source
  .github/workflows/daily_workflow.yml
  .github/workflows/workflow.yml
  docs/source/class_source.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/quickstart.rst
  gallery/experiments/experimental_abinitio_pipeline_10028.py
  gallery/experiments/experimental_abinitio_pipeline_10073.py
  gallery/experiments/experimental_abinitio_pipeline_10081.py
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/class_averaging.py
  gallery/tutorials/pipeline_demo.py
  setup.py
  src/aspire/classification/__init__.py
  src/aspire/classification/averager2d.py
  src/aspire/classification/class2d.py
  src/aspire/classification/class_selection.py
  src/aspire/classification/rir_class2d.py
  src/aspire/denoising/__init__.py
  src/aspire/denoising/class_avg.py
  src/aspire/denoising/denoised_src.py
  src/aspire/image/__init__.py
  src/aspire/image/image_stacker.py
  src/aspire/source/image.py
  tests/test_class2D.py
  tests/test_class_src.py
  tests/test_image_stacker.py
  tox.ini
Labels: enhancement

#913 Add seed to flaky class average test
  src/aspire/classification/legacy_implementations.py
  src/aspire/classification/rir_class2d.py
  src/aspire/utils/random.py
  tests/test_class2D.py
Labels: bug, CI, cleanup

#882 Feature demo breakup
  docs/source/class_source.rst
  docs/source/quickstart.rst
  gallery/experiments/README.rst
  gallery/experiments/experimental_abinitio_pipeline_10028.py
  gallery/experiments/experimental_abinitio_pipeline_10073.py
  gallery/experiments/experimental_abinitio_pipeline_10081.py
  gallery/experiments/preprocess_imgs_exp.py.dontrun
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/README.rst
  gallery/tutorials/aspire_introduction.py
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/pipeline_demo.py
  gallery/tutorials/tutorials/README.rst
  gallery/tutorials/tutorials/apple_picker.py
  gallery/tutorials/tutorials/basic_image_array.py
  gallery/tutorials/tutorials/class_averaging.py
  gallery/tutorials/tutorials/cov2d_simulation.py
  gallery/tutorials/tutorials/cov3d_simulation.py
  gallery/tutorials/tutorials/ctf.py
  gallery/tutorials/tutorials/generating_volume_projections.py
  gallery/tutorials/tutorials/image_class.py
  gallery/tutorials/tutorials/image_expansion.py
  gallery/tutorials/tutorials/orient3d_simulation.py
  gallery/tutorials/tutorials/preprocess_imgs_sim.py
  gallery/tutorials/tutorials/starfile.py
  src/aspire/abinitio/commonline_base.py
  src/aspire/source/image.py
  tox.ini
Labels: documentation, enhancement, cleanup

#919 AsymmetricVolume Patch
  src/aspire/volume/volume_synthesis.py
Labels: bug

#902 Immutable operations
  environment-accelerate.yml
  environment-default.yml
  environment-intel.yml
  environment-openblas.yml
  gallery/experiments/cov2d_experiment.py.dontrun
  gallery/experiments/cov3d_experiment.dontrun
  gallery/experiments/experimental_abinitio_pipeline_10028.py
  gallery/experiments/experimental_abinitio_pipeline_10073.py
  gallery/experiments/experimental_abinitio_pipeline_10081.py
  gallery/experiments/preprocess_imgs_exp.py.dontrun
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/aspire_introduction.py
  gallery/tutorials/pipeline_demo.py
  gallery/tutorials/tutorials/basic_image_array.py
  gallery/tutorials/tutorials/ctf.py
  gallery/tutorials/tutorials/preprocess_imgs_sim.py
  gallery/tutorials/tutorials/starfile.py
  setup.py
  src/aspire/commands/cov3d.py
  src/aspire/commands/denoise.py
  src/aspire/commands/extract_particles.py
  src/aspire/commands/preprocess.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/denoising/class_avg.py
  src/aspire/denoising/denoised_src.py
  src/aspire/source/coordinates.py
  src/aspire/source/image.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  src/aspire/storage/starfile.py
  src/aspire/utils/relion_interop.py
  tests/test_class2D.py
  tests/test_class_src.py
  tests/test_coordinate_source.py
  tests/test_downsample.py
  tests/test_load_images.py
  tests/test_preprocess_pipeline.py
  tests/test_simulation.py
  tests/test_simulation_metadata.py
  tests/test_starfile_stack.py
  tests/test_starfileio.py
Labels: enhancement, cleanup

#930 add missing assignment in 10073
  gallery/experiments/experimental_abinitio_pipeline_10073.py
Labels: bug, documentation, cleanup

#931 Workaround patches
  .github/workflows/workflow.yml
  gallery/experiments/experimental_abinitio_pipeline_10028.py
  gallery/experiments/experimental_abinitio_pipeline_10081.py
  src/aspire/source/coordinates.py
  src/aspire/source/relion.py
Labels: bug, invalid, cleanup
