Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-02, with the labels that each got.

#847 black 23.1.0 release
  src/aspire/abinitio/commonline_c3_c4.py
  src/aspire/apple/picking.py
  src/aspire/basis/ffb_3d.py
  src/aspire/basis/fspca.py
  src/aspire/basis/steerable.py
  src/aspire/classification/averager2d.py
  src/aspire/covariance/covar2d.py
  src/aspire/denoising/class_avg.py
  src/aspire/image/image.py
  src/aspire/numeric/complex_pca/validation.py
  src/aspire/numeric/numpy.py
  src/aspire/numeric/pyfftw_fft.py
  src/aspire/operators/filters.py
  src/aspire/operators/wemd.py
  src/aspire/source/image.py
  src/aspire/utils/cell.py
  tests/test_BlkDiagMatrix.py
  tests/test_adaptive_support.py
  tests/test_apple.py
  tests/test_averager2d.py
  tests/test_mrc.py
  tests/test_orient_symmetric.py
Labels: CI, cleanup, extern

#854 Long running tests 814
  .github/workflows/long_workflow.yml
  tests/test_covar3d.py
Labels: CI

#806 RELION 3.0 and 3.1 STAR file support
  src/aspire/source/coordinates.py
  src/aspire/source/relion.py
  src/aspire/utils/__init__.py
  src/aspire/utils/relion_interop.py
  tests/saved_test_data/sample_particles_relion30.star
  tests/saved_test_data/sample_particles_relion31.star
  tests/test_coordinate_source.py
  tests/test_orient_sync.py
  tests/test_starfile_stack.py
  tests/test_starfileio.py
Labels: enhancement, cleanup, extern

#853 Negative indexed slice bug
  src/aspire/source/image.py
  tests/test_load_images.py
Labels: bug

#858 Fle basis odd patch
  src/aspire/basis/fle_2d.py
  tests/test_FLEbasis2D.py
Labels: bug, enhancement, cleanup

#693 FLE Basis
  src/aspire/basis/__init__.py
  src/aspire/basis/fle_2d.py
  src/aspire/basis/fle_2d_utils.py
  src/aspire/basis/steerable.py
  src/aspire/nufft/__init__.py
  tests/saved_test_data/fle_radial_fn_32x32.npy
  tests/test_FLEbasis2D.py
Labels: enhancement, Optimization

#848 Remove `parameterized_class` from SyntheticVolume tests
  tests/test_synthetic_volume.py
Labels: CI, cleanup

#836 Conda backend opts
  .github/workflows/workflow.yml
  README.md
  azure-pipelines.yml
  docs/source/installation.rst
  environment-accelerate.yml
  environment-default.yml
  environment-intel.yml
  environment-openblas.yml
  environment.yml
  setup.py
  src/aspire/__init__.py
  src/aspire/config_default.yaml
  src/aspire/numeric/__init__.py
  src/aspire/numeric/mkl_fft.py
  tests/test_array_image_source.py
  tests/test_orient_symmetric.py
  tox.ini
Labels: enhancement, CI, Optimization, dependencies

#850 Ctf fwd validation
  docs/source/conf.py
  gallery/tutorials/ctf.py
  gallery/tutorials/data/ctffind4/diagnostic_output.png
  gallery/tutorials/data/ctffind4/diagnostic_output.txt
  gallery/tutorials/data/ctffind4/diagnostic_output_avrot.png
  gallery/tutorials/data/ctffind4/input.txt
  src/aspire/ctf/ctf_estimator.py
  src/aspire/operators/filters.py
  tox.ini
Labels: documentation, enhancement, cleanup

#857 Lecture Feature Demo Updates
  gallery/tutorials/lecture_feature_demo.py
Labels: documentation, cleanup

#860 Workaround grpc#32163
  setup.py
Labels: bug, extern, dependencies

#865 Downgrade windows CI from 2022 to 2019 (fixes single test fail in CI)
  .github/workflows/workflow.yml
Labels: bug, CI
