Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-06, with the labels that each got.

#961 Cuf13
  pyproject.toml
  tests/test_FLEbasis2D.py
Labels: CI, cleanup, extern, dependencies

#965 Apple bug
  src/aspire/apple/picking.py
  tests/test_apple.py
Labels: bug, CI, dependencies

#970 `osx-arm` notes
  README.md
  docs/source/installation.rst
Labels: documentation, extern, support, dependencies
