Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2023-03, with the labels that each got.

#870 Minor ctf tweaks
  gallery/tutorials/ctf.py
  src/aspire/ctf/ctf_estimator.py
  tests/test_CtfEstimate.py
Labels: bug, documentation, cleanup

#874 Demo dry run updates
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/pipeline_demo.py
Labels: documentation, cleanup

#839 SNR utils
  gallery/tutorials/pipeline_demo.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/noise/noise.py
  src/aspire/operators/__init__.py
  src/aspire/operators/filters.py
  src/aspire/source/image.py
  src/aspire/source/simulation.py
  src/aspire/utils/__init__.py
  src/aspire/utils/misc.py
  src/aspire/utils/units.py
  tests/test_imaging.py
  tests/test_noise.py
Labels: enhancement, cleanup

#863 Img vol return
  src/aspire/covariance/covar.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/image/image.py
  src/aspire/image/xform.py
  src/aspire/noise/noise.py
  src/aspire/reconstruction/kernel.py
  src/aspire/source/coordinates.py
  src/aspire/source/image.py
  src/aspire/source/relion.py
  src/aspire/source/simulation.py
  src/aspire/volume/volume.py
  tests/test_FFBbasis2D.py
  tests/test_FLEbasis2D.py
  tests/test_coordinate_source.py
  tests/test_downsample.py
  tests/test_mean_estimator.py
  tests/test_simulation.py
  tests/test_starfile_stack.py
  tests/test_synthetic_volume.py
  tests/test_volume.py
Labels: enhancement, cleanup

#879 Show patch
  src/aspire/image/image.py
  tests/test_image.py
  tests/test_simulation.py
  tests/test_utils.py
Labels: bug

#884 Missed img vol return tutorial updates
  gallery/experiments/experimental_abinitio_pipeline.py
  gallery/experiments/simulated_abinitio_pipeline.py
  gallery/tutorials/basic_image_array.py
  gallery/tutorials/class_averaging.py
  gallery/tutorials/cov2d_simulation.py
  gallery/tutorials/cov3d_simulation.py
  gallery/tutorials/image_expansion.py
  gallery/tutorials/lecture_feature_demo.py
  gallery/tutorials/starfile.py
Labels: bug, documentation, cleanup

#888 Asnumpy writable
  gallery/tutorials/basic_image_array.py
  src/aspire/ctf/ctf_estimator.py
  src/aspire/image/image.py
  src/aspire/volume/volume.py
  tests/test_image.py
  tests/test_volume.py
Labels: enhancement, good first issue, cleanup

#733 Ab-initio Cn
  src/aspire/abinitio/__init__.py
  src/aspire/abinitio/commonline_c3_c4.py
  src/aspire/abinitio/commonline_cn.py
  src/aspire/utils/__init__.py
  src/aspire/utils/matrix.py
  src/aspire/utils/misc.py
  tests/test_matrix.py
  tests/test_orient_symmetric.py
  tests/test_utils.py
Labels: enhancement
