Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2024-01, with the labels that each got.

#1074 CUDA 12 Support
  .github/workflows/workflow.yml
  pyproject.toml
Labels: enhancement, CI, extern, dependencies

#1077 Black updates
  gallery/tutorials/tutorials/apple_picker.py
  gallery/tutorials/tutorials/basic_image_array.py
  gallery/tutorials/tutorials/cov3d_simulation.py
  gallery/tutorials/tutorials/preprocess_imgs_sim.py
  src/aspire/basis/fpswf_2d.py
  src/aspire/image/image.py
  src/aspire/utils/logging.py
  src/aspire/utils/misc.py
  src/aspire/utils/resolution_estimation.py
Labels: cleanup, extern, dependencies

#1076 Bug fix for `evaluate_src_filters_on_grid`
  src/aspire/operators/filters.py
Labels: bug
