Repository ComputationalCryoEM/ASPIRE-Python, pull requests merged in 2025-05, with the labels that each got.

#1264 BOT_align Flaky Test
  src/aspire/utils/bot_align.py
  tests/test_bot_align.py
Labels: CI

#1270 Remove Numpy2 warning
  src/aspire/__init__.py
Labels: cleanup

#1278 Cast on Volume.rotate dtype mismatch
  src/aspire/volume/volume.py
Labels: support
